permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "shoeland"
  description: |
    A shoe selling business, specializing in customer choice.
  font_url: "https://fonts.googleapis.com/css?family=Open+Sans:400,700"
  colors:
    background: "#e2eade"
  color.primary: |
    The primary colour is red
  color.secondary: |
    The primary colour is black

  layouts:
    default: |
      The default layout should be used for almost evrey page, it includes the website's header & footer.
  font_url: "https://fonts.googleapis.com/css?family=Rock+Salt"

collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
