title: "Sections"
description: |
  Sections are are complete components that make a website.

patterns:
  product-details:
    title: "Product details"
    description: |
      The main top of page banner is used first on the product list page to catch the attention of a visitor and encourage them to shop.
  terms:
    title: Terms and conditions
    description: |
      This is the terms and conditions section.
  shipping-option:
    title: Shipping option
    description: |
      This denotes the shipping option of the product.
  shipping-address:
    title: Shipping Address
    description: |
      This denotes the shipping address of the product.
  bulk-pricing:
    title: Bulk Pricing
    description: |
      This is a table that shows the bulk pricing of various products.
  payment-info:
    title: Payment info
    description: |
      This is the payment info of the checkout.
  cookie:
    title: Cookie
    description: |
      This is a table that shows the bulk pricing of various products.
  return-policy:
    title: Return policy
    description: |
      This is the payment info of the checkout.
