title: "Card"
description: |
  Cards are small information snippets.

patterns:
  card:
    title: Card
    description: |
      The is a basic card.
  sectioncard:
    title: Section card
    description: |
      The is a grouping of the basic card.
